# Generated by Django 5.1.7 on 2025-04-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musabaqah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateuser',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
