# Generated by Django 5.1.7 on 2025-04-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musabaqah', '0002_alter_stateuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$v8Z7Jfk2ZY5dEK2YNDiaeA$3Mo6D7yzsN7JjeqnXAe7Sa/QlF6S8zxK7UhUnuCj3Uw=', max_length=128),
        ),
    ]
