# Generated by Django 5.1.7 on 2025-04-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musabaqah', '0003_stateuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$EAeAv3rmU26QKMZpCGz6TS$kdkA1L34U+X3snpqEbu+q2ltdrFDh5vj1QET0CSyOs4=', max_length=128),
        ),
    ]
