# Generated by Django 5.1.7 on 2025-04-30 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musabaqah', '0004_alter_stateuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$l9NRDa0GMCy0We1cQuQ5yq$8TqqQJQl+SoHV3oaOosNZWg2hMj42d/Rq/+khfpoZ9s=', max_length=128),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('hibz', models.CharField(choices=[('1st', '60Hibz'), ('2nd', '40Hibz'), ('3rd', '20Hibz'), ('4th', '10Hibz'), ('5th', '2Hibz')], max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('state_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musabaqah.stateuser')),
            ],
        ),
    ]
