# Generated by Django 5.1.7 on 2025-04-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musabaqah', '0005_alter_stateuser_password_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$ptkdh7Md1ValspKPGdcKRv$Qz4W6vHP/NLPlbpYjC2ZvAvn6fssdWqhWQ/u+ZtN3dc=', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('hibz', 'gender'), name='unique_hibz_per_gender'),
        ),
    ]
