# Generated by Django 5.1.7 on 2025-05-04 15:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musabaqah', '0009_remove_post_author_remove_post_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='stateuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$rdAxHh7gBzDwqgm6KsWTYs$8rpkIPq+YH8COVSguMWnM9lQps5mcQhf2cxJ5fEv0TE=', max_length=128),
        ),
    ]
