# Generated by Django 5.1.7 on 2025-05-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musabaqah', '0011_remove_post_content_post_author_post_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$klzI60PGCANEfWCz7OsLRY$1NABRObAo22bh0BGReVz6hJKa/hS/B54A6UGGEJVkpE=', max_length=128),
        ),
    ]
