# Generated by Django 5.1.7 on 2025-05-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musabaqah', '0015_alter_stateuser_password_alter_stateuser_state'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participant',
            name='unique_hibz_per_gender',
        ),
        migrations.AlterField(
            model_name='stateuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$sGzudwHD8jSxfoqx10t6tU$unidf25NMaPc15wLhaZtXrx068o0mCYpynh3fGcCNE0=', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('state_user', 'hibz', 'gender'), name='unique_participant_per_state_category_gender'),
        ),
    ]
